### ISSUE TITLE
Issue With Latency-Wait

### ISSUE THREAD

**Issue by joshuakirsch** [bhattlab/MGEfinder#15]
Hi,

I am trying to use MGEfinder but I keep getting this error:

Error in job make_database while creating output files sample5dir/02.database/v583_ncbi_genome/v583_ncbi_genome.database.fna, sample5dir/02.database/v583_ncbi_genome/v583_ncbi_genome.database.fna.1.bt2.
MissingOutputException in line 192 of /Users/duerkoplab/opt/miniconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile:
Missing files after 5 seconds:
sample5dir/02.database/v583_ncbi_genome/v583_ncbi_genome.database.fna
sample5dir/02.database/v583_ncbi_genome/v583_ncbi_genome.database.fna.1.bt2
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.

I can't find anything in the manual about --latency-wait. Can you please advise on what I should do?

Thanks!

**Comment by durrantmm** [comment]
Yes, this usually implies that it couldn't find any insertions.

Similar issue was brought up in #9 and #3.

You can check that with 

    wc -l sample5dir/01.mgefinder/*/*/*inferseq*

And if all of the files only have 1 line in them, then it didn't find any insertions.
