### ISSUE TITLE
Problem with clusterseq

### ISSUE THREAD

**Issue by mrozwandowicz** [bhattlab/MGEfinder#16]
Hi, 

I am very excited about using mgefinder, but so far I cannot make it work. I successfully run the script with a test dataset. However, multiple trials with different isolates and different reference genomes gave me the same error.

Error in job clusterseq while creating output file workdir/03.results/R27/01.clusterseq.R27.tsv.
RuleException:
CalledProcessError in line 259 of /home/rozwandm/.conda/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile:
Command 'mgefinder clusterseq -minsize 70 -maxsize 200000 --threads 1         --memory 16000 workdir/01.mgefinder/R27/R27.all_inferseq_database.txt -o workdir/03.results/R27/01.clusterseq.R27.tsv' returned non-zero exit status 1.
  File "/home/rozwandm/.conda/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile", line 259, in __rule_clusterseq
  File "/home/rozwandm/.conda/envs/mgefinder/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message

Thank you in advance for your help, 
Marta

**Comment by durrantmm** [comment]
Hello!

Thanks for asking this.

What error do you get when you run:

    mgefinder clusterseq -minsize 70 -maxsize 200000 --threads 1 --memory 16000 workdir/01.mgefinder/R27/R27.all_inferseq_database.txt -o workdir/03.results/R27/01.clusterseq.R27.tsv

when the `mgefinder` conda environment is activated?

**Comment by mrozwandowicz** [comment]
I got this error message:

IndexError: list index out of range

**Comment by durrantmm** [comment]
This is a strange one, how many samples are you analyzing?

**Comment by mrozwandowicz** [comment]
I always tried one sample at the time. Because I had problems and I thought the reference genome might be the problem, I tried multiple references, but always one at the time.

**Comment by durrantmm** [comment]
Great, could you please send me one of the samples that failed so I can test it? Thanks.

**Comment by mrozwandowicz** [comment]
I send you all of the files on this email address: 
mdurrant@stanford.edu

**Comment by durrantmm** [comment]
Thanks for sending over your files.

I was able to recreate the error you found. The issue was with how you named the files in your working directory. Please refer to the [tutorial](https://github.com/bhattlab/MGEfinder/wiki/Tutorial) to see exactly how to set up your working directory.

You had it set up like this:

    workdir/
    ├── 00.assembly/
    │   └── 15S04545-4.fasta.fna
    ├── 00.bam/
    │   ├── 15S04545-4.bam
    │   └── 15S04545-4.bam.bai
    └── 00.genome/
        └── R27.fna

I fixed it so that it looked like this:

    workdir/
    ├── 00.assembly/
    │   └── 15S04545-4.fna
    ├── 00.bam/
    │   ├── 15S04545-4.R27.bam
    │   └── 15S04545-4.R27.bam.bai
    └── 00.genome/
        └── R27.fna

And that fixed it.

I hope that helps! Make sure you include all of your isolates in a single working directory.
