### ISSUE TITLE
How to use MGEfinder software to find MGE from assembled genome in spite of raw reads

### ISSUE THREAD

**Issue by shakti83kumar** [bhattlab/MGEfinder#21]
Hi Sir,
I want to use the MGEfinder tool to find mobile genetic elements from assembled genome despite raw reads. How can I implement this program?

**Comment by durrantmm** [comment]
Take a look at the mgefinder command "wholegenome." This feature hasn't been fully tested, but I have been using it myself and it seems to work well.

**Comment by shakti83kumar** [comment]
Dear Durrantmm Sir,
Thanks to reply me.
I will check mentioned commond.
