### ISSUE TITLE
Installation without conda or singularity

### ISSUE THREAD

**Issue by samfux84** [bhattlab/MGEfinder#24]
Hi,

On many HPC clusters, conda is not supported for several reasons and singularity is kind of the last resort if nothing else works. 

Would you mind to at least provide a list of the required dependencies for MGEfinder on the wiki of this github repository?

Then people would have a choice to decide if they want to use conda, singularity or if they provided the dependencies in a different way. I don't ask you to support this way of installing the software actively, but please at least provide the list of dependencies.

Best regards

Sam

**Comment by samfux84** [comment]
This issue is now open for almost six months without answer. From this I conclude that you don't plan to provide a list of dependencies of the MGEfinder. I will tell the cluster user who asked for installation of MGEfinder that we cannot provide the software on the HPC cluster of our university.

Please feel free to close this issue.

**Comment by durrantmm** [comment]
I apologize for the late reply. I believe the conda environment specifications should give you a list of dependencies:

https://github.com/bhattlab/MGEfinder/blob/master/env/conda_linux64.yaml

**Comment by samfux84** [comment]
Does MGEfinder really have 90 dependencies (that must be a nightmare to maintain the program that it does not break if it depends on that many other packages which can change any time)? Or is this just some standard set of conda packages and MGEfinder only needs some of the dependencies?

**Comment by durrantmm** [comment]
I suspect it's a standard set of conda packages, mixed in with the true dependencies. I'm afraid I'm not sure what the exact minimal dependencies would be.
________________________________
