### ISSUE TITLE
mgefinder issue

### ISSUE THREAD

**Issue by Rick-meinersmann** [bhattlab/MGEfinder#25]
mgefinder is giving me an error code I don't understand.  As far as I can tell the input files follow the specifications and everything should be up to date, loaded or updated in the last week.  Entire screen dump in in attached file.
[mge_screen-out.txt](https://github.com/bhattlab/MGEfinder/files/6533588/mge_screen-out.txt)

Pertinent part would seem to be:
click.echo('Loading file {num1}/{num2}: {f}'.format(num1=1, num2=len(inferseq_files), f=inferseq_files[0]))
IndexError: list index out of range
Error in job clusterseq while creating output file /home/rick/Documents/Campy-mge-test/03.results/AL111168/01.clusterseq.AL111168.tsv.
RuleException:
CalledProcessError in line 259 of /home/rick/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile:
Command '
        mgefinder clusterseq -minsize 70 -maxsize 200000 --threads 1         --memory 50000 /home/rick/Documents/Campy-mge-test/01.mgefinder/AL111168/AL111168.all_inferseq_database.txt -o /home/rick/Documents/Campy-mge-test/03.results/AL111168/01.clusterseq.AL111168.tsv
        ' returned non-zero exit status 1.
  File "/home/rick/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile", line 259, in __rule_clusterseq
  File "/home/rick/anaconda3/envs/mgefinder/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message

Thank you for any help,
Rick

**Comment by durrantmm** [comment]
Thank you for reporting this issue. Please follow my responses in #16, and see if that clarifies the issue. My guess is that it didn't find any insertions and it failed as a result on the clusterseq step.

**Comment by Rick-meinersmann** [comment]
I missed the format on the bam file names to include the name of the reference genome sequence.  On fixing that the program ran without any error calls.  Thank you.

**Comment by durrantmm** [comment]
Great! Glad you got it working.
