### ISSUE TITLE
Missing input file error when file is in directory

### ISSUE THREAD

**Issue by Kylies5** [bhattlab/MGEfinder#26]
Hello, I keep getting "MissingInputException" and "Missing input files for rule pair" when I run mgefinder workflow denote however, all files are in the correct directories. I have deleted them and remade the files with no luck. I have run MGEfinder previously without this error. 

============================================================
=====         Summary of your script job               =====
============================================================
  The script file is: mgefinderworkflow.sh
  The time limit is 150:00:00 HH:MM:SS.
  The target directory is: /scratch/aubksw/MGEfinder/MGEfinder/cluster4
  The working directory is:  /scratch-local/aubksw.mgefinderworkflows.601211
  The memory limit is: 8gb
  The job will start running after: 2021-06-12T13:43:22
  Job Name: mgefinderworkflows
  Virtual queue: medium
  QOS: --qos=medium
  Constraints: --constraint=dmc
  Using  6  cores on master node  dmc19
  Node list:  dmc19
  Nodes:  dmc19 dmc19 dmc19 dmc19 dmc19 dmc19
  Command typed:
/apps/scripts/run_script mgefinderworkflow.sh
  Queue submit command:
sbatch --qos=medium -J mgefinderworkflows --begin=2021-06-12T13:43:22 --requeue --mail-user=ksw0029@auburn.edu -o mgefinderworkflows.o601211 -t 150:00:00$
#### CHECKING DEPENDENCIES ####
Current version of snakemake: 3.13.3
Expected version of snakemake: 3.13.3
Current version of einverted: EMBOSS:6.6.0.0
Expected version of einverted: EMBOSS:6.6.0.0
Current version of bowtie2: 2.3.5
Expected version of bowtie2: 2.3.5
Current version of samtools: 1.9
Expected version of samtools: 1.9
Current version of cd-hit: 4.8.1
Expected version of cd-hit: 4.8.1
###############################
Get help documentation with --help.
Get version with --version.
#### PARAMETERS ####
command: workflow
workdir: /scratch/aubksw/MGEfinder/MGEfinder/cluster4
cores: 1
memory: 16000
unlock: False
rerun_incomplete: False
keep_going: False
sensitive: False
####################
MissingInputException in line 93 of /home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile:
Missing input files for rule pair:
/scratch/aubksw/MGEfinder/MGEfinder/cluster4/00.bam/Xsp60.XretroflexusSp953.bam
COMMAND: snakemake -s /home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile --config wd=/scratch$
Traceback (most recent call last):
  File "/home/aubksw/anaconda3/envs/mgefinder/bin/mgefinder", line 8, in <module>
    sys.exit(cli())
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/main.py", line 78, in denovo
    _workflow(workdir, snakefile, configfile, cores, memory, unlock, rerun_incomplete, keep_going)
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow.py", line 25, in _workflow
    shell(cmd)
  File "/home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/snakemake/shell.py", line 88, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'snakemake -s /home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original$

**Comment by qianxin-kxy** [comment]
Hello , I've also encountered this problem. How did you solve it in the end?

**Comment by Kylies5** [comment]
This error is usually caused by something wrong in the name or formatting of the file. The file names need to match exactly , including matching upper and lowercase. Check that the files names are all correct and that there are no duplicate named files

**Comment by qianxin-kxy** [comment]
> Thank you very much for your prompt reply. I have rechecked the file names in the folder and it was indeed an oversight to mistake a letter!

**Comment by qianxin-kxy** [comment]
> This error is usually caused by something wrong in the name or formatting of the file. The file names need to match exactly , including matching upper and lowercase. Check that the files names are all correct and that there are no duplicate named files

Thank you very much for your prompt reply. I have rechecked the file names in the folder and it was indeed an oversight to mistake a letter!
