### ISSUE TITLE
KeyError 

### ISSUE THREAD

**Issue by Kylies5** [bhattlab/MGEfinder#27]
Hello, do you know what is causing this error and how to fix it? 

KeyError: 'emb|FRDD01000003.1|'
Error in job pair while creating output file /scratch/aubksw/MGEfinder/MGEfinder/cluster4/01.mgefinder/XretroflexusSp953/Xsp60/02.pair.Xsp60.XretroflexusSp953.tsv.
RuleException:
CalledProcessError in line 109 of /home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile:
Command '
	mgefinder pair -maxdr 20 -minq 20 -minial 21 -maxjsp 0.15         -lins 30 /scratch/aubksw/MGEfinder/MGEfinder/cluster4/01.mgefinder/XretroflexusSp953/Xsp60/01.find.Xsp60.XretroflexusSp953.tsv $
        ' returned non-zero exit status 1.

**Comment by durrantmm** [comment]
Thanks for sharing this. Could you please send me the input files for this particular analysis? Not all of them, just the sample Xsp60.XretroflexusSp953

**Comment by Kylies5** [comment]
How do I send the files?

**Comment by durrantmm** [comment]
However you like, you can zip them up and attach them in your next response to this thread, for example.

**Comment by Kylies5** [comment]
Hello, here are the files:
00.genome - 
[XretroflexusSp953.fna.zip](https://github.com/bhattlab/MGEfinder/files/6704057/XretroflexusSp953.fna.zip)
00.assembly - 
[Xsp60.fna.zip](https://github.com/bhattlab/MGEfinder/files/6704062/Xsp60.fna.zip)

**Comment by Kylies5** [comment]
00.bam- 
[Xsp60.XretroflexusSp953.bam.bai.zip](https://github.com/bhattlab/MGEfinder/files/6704064/Xsp60.XretroflexusSp953.bam.bai.zip)

**Comment by Kylies5** [comment]
The other bam file will not upload

**Comment by durrantmm** [comment]
Ok, well I will need the BAM file. Could you upload it to google drive or dropbox and share a link?

**Comment by Kylies5** [comment]
https://drive.google.com/drive/folders/1vAACS7RxB_o1ap_Fy9dzVlGCP5QNOC3-?usp=sharing
