### ISSUE TITLE
No output file, no error message 

### ISSUE THREAD

**Issue by Kylies5** [bhattlab/MGEfinder#28]
Hello, I have tried running mgefinder on multiple data sets. Some have worked and some have not. My latest run produced this:

#### CHECKING DEPENDENCIES ####
Current version of snakemake: 3.13.3
Expected version of snakemake: 3.13.3
Current version of einverted: EMBOSS:6.6.0.0
Expected version of einverted: EMBOSS:6.6.0.0
Current version of bowtie2: 2.3.5
Expected version of bowtie2: 2.3.5
Current version of samtools: 1.9
Expected version of samtools: 1.9
Current version of cd-hit: 4.8.1
Expected version of cd-hit: 4.8.1
###############################
Get help documentation with --help.
Get version with --version.
#### PARAMETERS ####
command: workflow
workdir: /scratch/aubksw/MGEfinder/MGEfinder/cluster5
cores: 1
memory: 16000
unlock: False
rerun_incomplete: False
keep_going: False
sensitive: True
####################
COMMAND: snakemake -s /home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.sensitive.Snakefile --config wd=/scratch/aubksw/MGEfinder/MGEfinder/cluster5 memory=16000 --cores 1 --configfile /home/aubksw/anaconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.sensitive.config.yml 
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1

rule all:
    jobid: 0

Finished job 0.
1 of 1 steps (100%) done

There were no output files created and no error messages so I am not sure what went wrong. Please let me know if there is a solution. Thank you

**Comment by durrantmm** [comment]
This looks like an issue with the directory structure. Could you show me the files in your working directory?

**Comment by Kylies5** [comment]
<img width="520" alt="Screen Shot 2021-06-22 at 10 16 55 AM" src="https://user-images.githubusercontent.com/85805090/122951670-1267e380-d343-11eb-801a-8f6517cc1cdb.png">

**Comment by durrantmm** [comment]
I need to see the files in the directories `00.assembly`, `00.bam`, and `00.genome`.

**Comment by Kylies5** [comment]
aubksw@dmcvlogin4:cluster5> cd 00.assembly
(base) aubksw@dmcvlogin4:00.assembly> ls
XtranslucensF5.fna
(base) aubksw@dmcvlogin4:00.assembly> cd ..
(base) aubksw@dmcvlogin4:cluster5> cd 00.genome
(base) aubksw@dmcvlogin4:00.genome> ls
XtranslucensDSM18974.fsa
(base) aubksw@dmcvlogin4:00.genome> cd ..
(base) aubksw@dmcvlogin4:cluster5> cd 00.bam 
(base) aubksw@dmcvlogin4:00.bam> ls
XtranslucensF5.XtranslucensDSM18974.bam
XtranslucensF5.XtranslucensDSM18974.bam.bai

**Comment by Kylies5** [comment]
[XtranslucensDSM18974.fsa.zip](https://github.com/bhattlab/MGEfinder/files/6704110/XtranslucensDSM18974.fsa.zip)
[XtranslucensF5.XtranslucensDSM18974.bam.bai.zip](https://github.com/bhattlab/MGEfinder/files/6704111/XtranslucensF5.XtranslucensDSM18974.bam.bai.zip)
[XtranslucensF5.fna.zip](https://github.com/bhattlab/MGEfinder/files/6704112/XtranslucensF5.fna.zip)

**Comment by Kylies5** [comment]
XtranslucensF5.XtranslucensDSM18974.bam.zip

**Comment by durrantmm** [comment]
Ok, the way the files are named needs to match what is described [here](https://github.com/bhattlab/MGEfinder/wiki/Tutorial#downloading-the-test-dataset). The 00.genome file must end in `.fna` not `.fsa`.
