### ISSUE TITLE
filtering used to create *.all_seqs.fna file?

### ISSUE THREAD

**Issue by tracylnicholson** [bhattlab/MGEfinder#33]
In our data set there seems to be some filtering that occurred between the 01.clusterseq.<genome>.tsv and the *.all_seqs.fna files. Even after the 01.clusterseq.<genome>.tsv file was filtered to remove duplicates based on the sequence inference method, it contains far more MGE sequences than the *.all_seqs.fna file. Could you direct me where to look to find the filtering information that was used to create the *.all_seqs.fna file? My main concern is that the 01.clusterseq.<genome>.tsv file contains a high number of potentially false positive MGE sequences.
Thanks in advance for your help!

**Comment by durrantmm** [comment]
I think this should answer your question #30.

In summary, you shouldn't use the clusters in 01.clusterseq.tsv, a filtering step is applied to remove false positives. It's really just an intermediate file.

As discussed in the paper, additional MGE filtering may be necessary, depending on your goal. If you aren't especially interested in _de novo_ MGE discovery, you can only keep MGEs that contain known transposases, recombinases, etc.
