### ISSUE TITLE
How to find the Insertion-Enriched Sites caused by Insertion sequences

### ISSUE THREAD

**Issue by Daikuang** [bhattlab/MGEfinder#39]
Hi Matthew,
I’m very interested in the Analysis of Insertion-Enriched Sites in your paper.
I am trying to analyze Insertion-Enriched Sites caused by Insertion sequences (the upstream, within and downstream of the nearest CDS)  among 200 complete sequenced bacteria.
I wonder if I can use the MGEfinder tool to do this? 
If yes, Could you please give me some idea (or the workflow)?
Many thanks in advance.
Sincerely,
Dai Kuang

**Comment by durrantmm** [comment]
Yes, it certainly could be used to do that. The [wiki](https://github.com/bhattlab/MGEfinder/wiki) should help you get started with the MGEfinder command-line interface. This will identify insertions, but there is no software for automatically calculating which sites are enriched. I described how I did it in the [paper](https://www.cell.com/cell-host-microbe/fulltext/S1931-3128(19)30546-3?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1931312819305463%3Fshowall%3Dtrue). 
<img width="990" alt="image" src="https://user-images.githubusercontent.com/10098419/170579651-15114082-f54d-41ce-9a0b-241f43779b11.png">
