### ISSUE TITLE
Issue with pandas dependency

### ISSUE THREAD

**Issue by jordiabante** [bhattlab/MGEfinder#40]
Hi Matthew, 

I tried installing MGEfinder on Stanford's sherlock through conda and it seemed to finish successfully. However, the help command mgefinder —help results in the following error:

ModuleNotFoundError: No module named ‘pandas.compat'

I also tried installing a more up-to-date version of pandas, but still produces the same error. I figured you might be able to help me, considering that you probably used sherlock to develop the tool. Do you know what might be going on?

Thanks!

**Comment by durrantmm** [comment]
Hi! I actually didn't use sherlock to develop the tool. If possible, I would use the singularity installation for batch computing. I don't really know how to help you otherwise.

**Comment by abehr** [comment]
In case anyone else runs into this issue, it's caused by a known anaconda issue where conda environment supersedes its own libraries with ones installed in `.local` instead. We were able to fix it by setting env var `PYTHONNOUSERSITE`.

**Comment by durrantmm** [comment]
Great! Thank you for explaining this.
