### ISSUE TITLE
 Error in job genotype while creating output file 

### ISSUE THREAD

**Issue by Oelsakha** [bhattlab/MGEfinder#42]
Hi all 

I am trying to run test files of MGEfinder but I got this error

 
 
#### CHECKING DEPENDENCIES ####
Current version of snakemake: 3.13.3
Expected version of snakemake: 3.13.3
Current version of einverted: EMBOSS:6.6.0.0
Expected version of einverted: EMBOSS:6.6.0.0
Current version of bowtie2: 2.3.5
Expected version of bowtie2: 2.3.5
Current version of samtools: 1.9
Expected version of samtools: 1.9
Current version of cd-hit: 4.8.1
Expected version of cd-hit: 4.8.1
 :
 :
  Error in job genotype while creating output file 
 test_workdir/03.results/efae_GCF_900639545/02.genotype.efae_GCF_900639545.tsv.
RuleException:
CalledProcessError in line 286 of /Users/mo/miniconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile:
Command '
        if [ "True" == "True" ]; then
            mgefinder genotype --filter-clusters-inferred-assembly test_workdir/03.results/efae_GCF_900639545/01.clusterseq.efae_GCF_900639545.tsv test_workdir/01.mgefinder/efae_GCF_900639545/efae_GCF_900639545.all_pair.txt -o test_workdir/03.results/efae_GCF_900639545/02.genotype.efae_GCF_900639545.tsv 1> test_workdir/03.results/efae_GCF_900639545/log/efae_GCF_900639545.genotype.log 2> test_workdir/03.results/efae_GCF_900639545/log/efae_GCF_900639545.genotype.log.err ||             (cat test_workdir/03.results/efae_GCF_900639545/log/efae_GCF_900639545.genotype.log.err; exit 1)
        else
            mgefinder genotype --no-filter-clusters-inferred-assembly test_workdir/03.results/efae_GCF_900639545/01.clusterseq.efae_GCF_900639545.tsv test_workdir/01.mgefinder/efae_GCF_900639545/efae_GCF_900639545.all_pair.txt -o test_workdir/03.results/efae_GCF_900639545/02.genotype.efae_GCF_900639545.tsv 1> test_workdir/03.results/efae_GCF_900639545/log/efae_GCF_900639545.genotype.log 2> test_workdir/03.results/efae_GCF_900639545/log/efae_GCF_900639545.genotype.log.err ||             (cat test_workdir/03.results/efae_GCF_900639545/log/efae_GCF_900639545.genotype.log.err; exit 1)
        fi
        ' returned non-zero exit status 1.
  File "/Users/mo/miniconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile", line 286, in __rule_genotype
  File "/Users/mo/miniconda3/envs/mgefinder/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
:

:
subprocess.CalledProcessError: Command 'snakemake -s /Users/mo/miniconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.Snakefile --config wd=test_workdir/ memory=16000 --cores 1 --configfile /Users/mo/miniconda3/envs/mgefinder/lib/python3.6/site-packages/mgefinder/workflow/denovo.original.config.yml ' returned non-zero exit status 1.

**Comment by durrantmm** [comment]
Looks like an issue with snakemake. How did you install MGEfinder?

**Comment by Oelsakha** [comment]
**I already have conda so i did this step** 
     git clone https://github.com/bhattlab/MGEfinder.git
     cd MGEfinder/
     bash install.sh
     **However, I removed MGEfinder and reinstall it and found this new error.** 
     
     Traceback (most recent call last):
  File "/Users/mo/miniconda3/bin/mgefinder", line 33, in <module>
    sys.exit(load_entry_point('mgefinder==1.0.6', 'console_scripts', 'mgefinder')())
  File "/Users/mo/miniconda3/bin/mgefinder", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/mo/miniconda3/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/Users/mo/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/mo/miniconda3/lib/python3.9/site-packages/mgefinder-1.0.6-py3.9.egg/mgefinder/main.py", line 5, in <module>
    from mgefinder.workflow import _workflow
  File "/Users/mo/miniconda3/lib/python3.9/site-packages/mgefinder-1.0.6-py3.9.egg/mgefinder/workflow.py", line 2, in <module>
    from snakemake import shell
ModuleNotFoundError: No module named 'snakemake'

**Comment by durrantmm** [comment]
Seems like a clean install is needed here. I assume you're also calling `conda activate mgefinder`?

**Comment by Oelsakha** [comment]
can you explain more? 
I removed it then reinstalled and conda activate mgefinder
now give me this error 
zsh: command not found: mgefinder

**Comment by durrantmm** [comment]
You need to activate the conda environment that includes the mgefinder installation. This seems like an issue with your conda installation. Could you give me the exact output when you run the command:

```
conda activate mgefinder
```

**Comment by Oelsakha** [comment]
Yes, I did and mgefinder env is activated but if I run it give me zsh: command not found: mgefinder

**Comment by durrantmm** [comment]
Then it didn't install properly. Could you uninstall, reinstall, and send me the complete output?
