### ISSUE TITLE
MGE for FASTA format

### ISSUE THREAD

**Issue by leggylas** [bhattlab/MGEfinder#44]
I have a FASTA file assembled already, is it possible to use this file in MGEfinder to detect any MGE that is present in my sequence? 

If so, what is the code I should use to run the system? Since the tutorial mostly focuses on non-assembled files..

Thanks

**Comment by durrantmm** [comment]
Yes, you can take a look at the `mgefinder wholegenome` command. It hasn't been tested like the other features of the tool, and it won't perform much better than something like Mauve, but it's worth trying!
